### ISSUE TITLE
Registration Form CSS not rendering correctly

### ISSUE THREAD

**Issue by fai2an** [Maddy4769/Gym-Web-app#2]
The CSS for the registration form is not rendering as expected. The form appears visually unappealing and may not be user-friendly.

**Comment by Maddy4769** [comment]
Okay i will Check the error and update the CSS for it

**Comment by Maddy4769** [comment]
@fai2an i have update the CSS of form please and revert back asap

**Comment by Maddy4769** [comment]
CSS has been completed
