### ISSUE TITLE
Registration Form Lacks Nutrition & Yoga Plan Selection Options

### ISSUE THREAD

**Issue by fai2an** [Maddy4769/Gym-Web-app#3]
The current registration form does not provide options for users to select their preferred nutrition and yoga plans. Including these options would allow for a more personalized user experience

Would like the registration form to include sections where users can choose their desired nutrition and yoga plans from predefined options.

**Comment by Maddy4769** [comment]
The nutrition and yoga plan option have been added to form and are working fine with backend
